HOSTS:
  centos-7-x64:
    roles:
      - master
      - agent
      - default
    platform: el-7-x86_64
    box:  puppetlabs/centos-7.0-64-puppet
    hypervisor: vagrant
    auto_config: true
    vagrant_memsize: 4096
CONFIG:
  type: foss
