HOSTS:
  centos-65-x64:
    roles:
      - master
      - agent
      - default
    platform: el-5-x86_64
    box:  puppetlabs/centos-6.5-64-nocm
    hypervisor: vagrant
    provider: vmware_fusion
CONFIG:
  type: foss
